spring.application.name = archeo-hub
spring.main.banner-mode = off
server.port = 4000

spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view = false

cadence.domain.name = archeo-domain
cadence.domain.retention = 30
cadence.task-list = ArcheoTaskList

workflow.source-bucket = inbox
workflow.work-bucket = work
#workflow.archive-bucket = work
